# Generated by Django 4.0.4 on 2022-05-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='subject',
            field=models.CharField(choices=[('P', 'Peticiones'), ('Q', 'Quejas'), ('R', 'Reclamos'), ('S', 'Sugerencias')], max_length=200, null=True, verbose_name='Procedimiento'),
        ),
    ]
