# Generated by Django 4.0.4 on 2022-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('service', models.CharField(max_length=200, verbose_name='Servicio')),
                ('message', models.TextField(null=True, verbose_name='Mensaje')),
                ('status', models.BooleanField(default=False, verbose_name='Atendido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
