# Generated by Django 4.0.4 on 2022-05-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_cita_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-created'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Cita'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='date',
            field=models.DateTimeField(max_length=200, verbose_name='Fecha de la cita'),
        ),
    ]
