# Generated by Django 4.0.4 on 2022-05-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('cita', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Doctor(a)'),
        ),
    ]
