# Generated by Django 4.0.4 on 2022-05-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_alter_cita_options_alter_cita_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-created'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cita'),
        ),
    ]
