# Generated by Django 4.0.4 on 2022-05-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_alter_cita_options_alter_cita_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='date',
        ),
    ]
